import React, { useState } from 'react';
import { 
  MessageCircle, 
  BookOpen, 
  Users, 
  GraduationCap, 
  Home, 
  ChevronRight, 
  Star,
  CheckCircle,
  Sparkles,
  Target,
  Heart,
  Zap,
  Library,
  Book,
  Play
} from 'lucide-react';

function App() {
  const [activeTab, setActiveTab] = useState('teachers');

  const audiences = {
    teachers: {
      icon: <GraduationCap className="w-6 h-6" />,
      title: "Teachers",
      description: "Enhance your literature curriculum with AI-powered insights",
      features: [
        "Quickly fact-check literary information to ensure accuracy when teaching or answering student questions",
        "Deepen your own understanding of complex texts through expert-level analysis, author background, and critical interpretations",
        "Clarify complex literary concepts (themes, symbolism, character arcs) on demand",
        "Get quick refreshers or summaries to prep for class discussions or lesson planning"
      ]
    },
    students: {
      icon: <BookOpen className="w-6 h-6" />,
      title: "Students",
      description: "Get instant help with your reading assignments and homework",
      features: [
        "Ask anything about a book and get clear, accurate answers instantly",
        "Get help breaking down difficult passages, themes, or historical context",
        "Generate essay prompts and outlines based on the book you're reading",
        "Study smarter with guided insights on characters, symbols, and key moments"
      ]
    },
    bookClubs: {
      icon: <Users className="w-6 h-6" />,
      title: "Book Club Members",
      description: "Elevate your discussions with expert literary insights",
      features: [
        "Elevate your discussions with expert literary insights",
        "Generate thought-provoking discussion questions",
        "Explore deeper themes and connections across characters and events",
        "Access historical and cultural context to enrich conversations"
      ]
    },
    parents: {
      icon: <Home className="w-6 h-6" />,
      title: "Parents",
      description: "Support your child's reading journey with confidence",
      features: [
        "Understand what your child is reading with quick summaries and guides",
        "Find age-appropriate discussion questions to talk about books at home",
        "Support homework and reading comprehension with easy-to-grasp explanations",
        "Discover similar books that match your child's interests and grade level"
      ]
    },
    librarians: {
      icon: <Library className="w-6 h-6" />,
      title: "Librarians",
      description: "Enhance library services with comprehensive literary resources",
      features: [
        "Recommend books confidently with fast access to summaries and themes",
        "Answer readers' questions about authors, genres, or literary elements on the spot",
        "Generate activity ideas or reading guides for programs and events",
        "Compare titles or authors to help patrons find their next favorite read"
      ]
    },
    readers: {
      icon: <Book className="w-6 h-6" />,
      title: "General Readers",
      description: "Deepen your appreciation and understanding of any book",
      features: [
        "Ask questions while reading to understand plot points, symbols, or characters",
        "Explore deeper layers of meaning without reading multiple sources",
        "Compare the book to others by the same author or in the same genre",
        "Get fast recaps or scene breakdowns when revisiting a story or catching up"
      ]
    }
  };

  const testimonials = [
    {
      name: "Sarah Johnson",
      role: "High School English Teacher",
      audience: "teacher",
      text: "AskSupersummary has revolutionized how I prepare lessons. I can generate comprehensive discussion questions and activities in minutes, not hours.",
      rating: 5
    },
    {
      name: "Marcus Chen",
      role: "College Student",
      audience: "student", 
      text: "When I was struggling with Moby Dick, AskSupersummary helped me understand the symbolism and themes. My essay grade improved dramatically!",
      rating: 5
    },
    {
      name: "Jennifer Martinez",
      role: "Book Club Leader",
      audience: "bookClub",
      text: "Our book club discussions have never been more engaging. AskSupersummary provides insights we never would have discovered on our own.",
      rating: 5
    },
    {
      name: "Lisa Rodriguez",
      role: "Middle School Teacher",
      audience: "teacher",
      text: "The classroom activities generated by AskSupersummary are creative and perfectly aligned with my curriculum goals. My students love them!",
      rating: 5
    },
    {
      name: "Emma Wilson",
      role: "Graduate Student",
      audience: "student",
      text: "For my thesis on Victorian literature, AskSupersummary provided contextual information and analysis that would have taken weeks to research.",
      rating: 5
    },
    {
      name: "Rachel Green",
      role: "Avid Reader",
      audience: "reader",
      text: "I love how AskSupersummary helps me discover deeper meanings in books I thought I understood. It's transformed my reading experience completely.",
      rating: 5
    }
  ];

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-[#33a9b5] to-[#1f7f89] text-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-5xl md:text-6xl font-bold mb-6">
              Your AI Literary Expert
            </h1>
            <p className="text-xl md:text-2xl mb-8 max-w-3xl mx-auto opacity-90">
              Your intelligent companion for exploring literature - get instant insights, discover hidden meanings, and unlock the full potential of every book you read
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a 
                href="https://www.supersummary.com/sign-in/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="bg-[#187987] hover:bg-white hover:text-[#187987] px-8 py-4 rounded-lg font-semibold text-lg transition-all transform hover:scale-105 inline-block text-center"
              >
                Try AskSupersummary
              </a>
              <button 
                onClick={() => document.getElementById('video-demo')?.scrollIntoView({ behavior: 'smooth' })}
                className="border-2 border-white hover:bg-white hover:text-[#187987] px-8 py-4 rounded-lg font-semibold text-lg transition-all"
              >
                Watch Demo
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Powerful Features for Every Reader
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              AskSupersummary combines deep literary knowledge with AI to provide instant, expert-level insights
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="bg-[#33a9b5] w-12 h-12 rounded-lg flex items-center justify-center mb-6">
                <Sparkles className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-4">Instant Literary Analysis</h3>
              <p className="text-gray-600">
                Get detailed analysis of themes, characters, symbolism, and plot points for any book in our extensive library
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="bg-[#33a9b5] w-12 h-12 rounded-lg flex items-center justify-center mb-6">
                <Target className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-4">Personalized Learning</h3>
              <p className="text-gray-600">
                Tailored responses based on your reading level, learning goals, and specific needs as a student, teacher, or reader
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="bg-[#33a9b5] w-12 h-12 rounded-lg flex items-center justify-center mb-6">
                <Zap className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-4">Resource Generation</h3>
              <p className="text-gray-600">
                Create discussion questions, lesson plans, study guides, and classroom activities in seconds
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="bg-[#33a9b5] w-12 h-12 rounded-lg flex items-center justify-center mb-6">
                <BookOpen className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-4">Comprehensive Library</h3>
              <p className="text-gray-600">
                Access insights on thousands of books, from classic literature to contemporary works across all genres
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="bg-[#33a9b5] w-12 h-12 rounded-lg flex items-center justify-center mb-6">
                <Heart className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-4">Contextual Information</h3>
              <p className="text-gray-600">
                Understand historical context, cultural background, and author biography to enrich your reading experience
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="bg-[#33a9b5] w-12 h-12 rounded-lg flex items-center justify-center mb-6">
                <Users className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold mb-4">Multi-Audience Support</h3>
              <p className="text-gray-600">
                Designed for teachers, students, book clubs, and parents with specialized features for each group
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Video Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              See AskSupersummary in Action
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Watch how AskSupersummary transforms the way you engage with literature
            </p>
          </div>
          
          <div className="max-w-4xl mx-auto">
            <div className="relative bg-gray-900 rounded-2xl overflow-hidden shadow-2xl">
              <img 
                src="https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=1200&h=675&fit=crop"
                alt="Video player placeholder showing AskSupersummary demo"
                className="w-full h-auto aspect-video object-cover"
              />
              <div className="absolute inset-0 bg-black bg-opacity-30 flex items-center justify-center">
                <div className="bg-white bg-opacity-20 backdrop-blur-sm rounded-full p-6 hover:bg-opacity-30 transition-all cursor-pointer group">
                  <Play className="w-16 h-16 text-white group-hover:scale-110 transition-transform" fill="currentColor" />
                </div>
              </div>
              <div className="absolute bottom-4 left-4 right-4">
                <div className="bg-black bg-opacity-50 backdrop-blur-sm rounded-lg p-4">
                  <h3 className="text-white font-semibold text-lg mb-1">
                    Getting Started with AskSupersummary
                  </h3>
                  <p className="text-gray-200 text-sm">
                    Learn how to unlock deeper insights from any book in minutes
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Audiences Section */}
      <section id="audiences" className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Perfect for Every Type of Reader
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Whether you're teaching, learning, or simply love books, AskSupersummary adapts to your needs
            </p>
          </div>

          <div className="flex flex-wrap justify-center gap-2 mb-8">
            {Object.entries(audiences).map(([key, audience]) => (
              <button
                key={key}
                onClick={() => setActiveTab(key)}
                className={`flex items-center space-x-2 px-6 py-3 rounded-lg font-medium transition-all ${
                  activeTab === key
                    ? 'bg-[#187987] text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {audience.icon}
                <span>{audience.title}</span>
              </button>
            ))}
          </div>

          <div className="bg-white rounded-2xl shadow-xl p-8 md:p-12">
            <div className="flex items-center space-x-4 mb-8">
              <div className="bg-[#33a9b5] w-12 h-12 rounded-lg flex items-center justify-center text-white">
                {audiences[activeTab].icon}
              </div>
              <div>
                <h3 className="text-3xl font-bold text-gray-900 mb-2">{audiences[activeTab].title}</h3>
                <p className="text-lg text-gray-600">{audiences[activeTab].description}</p>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
              {audiences[activeTab].features.map((feature, index) => (
                <div key={index} className="flex items-start space-x-4 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                  <div className="bg-[#33a9b5] w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                    <CheckCircle className="w-4 h-4 text-white" />
                  </div>
                  <div className="flex-1">
                    <p className="text-gray-800 leading-relaxed">{feature}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Loved by Readers Everywhere
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              See how AskSupersummary is transforming the way people engage with literature
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
                <div className="flex items-center space-x-1 mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
                <p className="text-gray-700 mb-6 italic">"{testimonial.text}"</p>
                <div className="border-t pt-4">
                  <div className="font-semibold text-gray-900">{testimonial.name}</div>
                  <div className="text-sm text-gray-600">{testimonial.role}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-[#33a9b5] text-white py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-4xl font-bold mb-6">
            Ready to Transform Your Reading Experience?
          </h2>
          <p className="text-xl mb-8 opacity-90">
            Join thousands of readers who are already discovering deeper insights with AskSupersummary
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="bg-[#187987] hover:bg-white hover:text-[#187987] px-8 py-4 rounded-lg font-semibold text-lg transition-all transform hover:scale-105 flex items-center justify-center space-x-2">
              <span>Get Started Now</span>
              <ChevronRight className="w-5 h-5" />
            </button>
            <button 
              onClick={() => document.getElementById('video-demo')?.scrollIntoView({ behavior: 'smooth' })}
              className="border-2 border-white hover:bg-white hover:text-[#187987] px-8 py-4 rounded-lg font-semibold text-lg transition-all"
            >
              Watch Demo
            </button>
            <a href="#features" className="border-2 border-white hover:bg-white hover:text-[#187987] px-8 py-4 rounded-lg font-semibold text-lg transition-all inline-block text-center">
              Learn More
            </a>
          </div>
        </div>
      </section>

    </div>
  );
}

export default App;